development:
  LOG:
    NOTIFIER:
      FILE: "log/notifier.log"
      LEVEL: INFO
    BOT:
      FILE: "log/bot.log"
      LEVEL: INFO

  BOT:
    TOKEN: "your-token"
    WEB_SERVER_HOST: "127.0.0.1"
    WEB_SERVER_PORT: 8000
    WEBHOOK_PATH: "/webhook"
    WEBHOOK_SECRET: "your-secret"
    BASE_WEBHOOK_URL: "https://your-domain.ru"
    ADMIN: your-admin-telegram-id

  DB:
    TYPE: postgresql+asyncpg
    NAME: your-db
    HOST: localhost
    USER: your-user
    PASSWORD: your-password
