development:
  # Log config
  LOG:
    QUEUE_NOTIFIER:
      FILE: "log/queue_notifiers.log"
      LEVEL: INFO
    VIRTUAL_CAMP_BOT:
      FILE: "log/virtual_camp_bot.log"
      LEVEL: INFO

  # Bot config
  BOT:
    TOKEN: "your-token"
    WEB_SERVER_HOST: "127.0.0.1"
    WEB_SERVER_PORT: 8000
    WEBHOOK_PATH: "/webhook"
    WEBHOOK_SECRET: "your-secret"
    BASE_WEBHOOK_URL: "https://your-domain.ru"

  # DB config
  DB:
    TYPE: postgresql+asyncpg
    NAME: your-db
    HOST: localhost
    USER: your-user
    PASSWORD: your-password
